-- the console shows the Zapier key on every visit, so `zapier_key` keeps the key itself beside its
-- hash. `key_hash` is untouched and still what a request is admitted by. `src/lib/server/db/schema.ts`
-- argues the column beside it.
--
-- no table is rebuilt. drizzle drafts one, because the column carries a check, and its copy step
-- selects `"key"` from a table that has no such column — so this is hand-written as a native
-- `ADD COLUMN` with the check on the column, which sqlite tests against the row already there.
-- none of the rebuild hand-edits apply, and there is no `CREATE TABLE` to hand-write `STRICT` onto.
--
-- no backfill: a key minted before this migration was never stored, so its row reads `key` null
-- until the key is replaced.
ALTER TABLE `zapier_key` ADD `key` text CONSTRAINT "zapier_key_key_check" CHECK("zapier_key"."key" is null or (length("zapier_key"."key") = 47 and "zapier_key"."key" glob 'bgz_*' and substr("zapier_key"."key", 5) not glob '*[^A-Za-z0-9_-]*'));
