import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

// the guard on "one module per processor SDK, and nothing else may import one".
//
// why this test exists. payments go through the `PaymentProvider` port and never a processor's SDK
// directly (CLAUDE.md), and until this file that was enforced by nothing — a convention, which is a
// code review somebody has to remember to do. it is the same guard ../ledger/sole-writer.spec.ts
// holds over `INSERT`, written the same way, and the rule it protects is the one ../db/client.ts
// states about D1: everything else takes the interface, so the contract has exactly one place to be
// stated.
//
// what the rule buys, concretely. the SDK's vocabulary — seven PaymentIntent states, sixteen
// error classes, unix seconds, lowercase currencies, expandable fields that are sometimes id
// strings — stops at one file, and ./provider.ts is what the rest of the app reads. a second
// importer is a second translation of all of that, written by whoever needed one field in a hurry,
// and the two disagree in exactly the places nobody looks.
//
// the tempting shortcut this exists to catch is a route handler reaching for `stripe.refunds` or
// `stripe.webhooks` because the port does not expose what it needs yet. the answer is to widen the
// port, which is a reviewable change, rather than to open a second channel to the processor.
//
// **a processor is guarded before its adapter is written, not after.** the shortcut above is taken
// in a hurry, and the hurry is at its worst on the day somebody is standing an adapter up — so an
// entry here costs nothing while the tree holds no importer for it, and is already standing when
// one arrives.
//
// it scans the whole repository rather than `src/`, because `src/` is not the whole repository:
// CLAUDE.md puts packages in `packages/*` consumable as source, and the root holds build and test
// configuration that is ordinary TypeScript and could import anything. a guard that stopped at
// `src/` would be silent about both.
//
// how it works: a source scan, not a runtime hook. a runtime one would only see the paths a test
// happens to exercise, and the importer that matters is exactly the one nobody wrote a test for.
// it reads text and can be fooled by a computed specifier — accepted, because what it defends
// against is a shortcut taken in a hurry, not an adversary.
//
// what is exempt: each processor's own adapter, and this file, which necessarily contains the
// patterns it searches for.

const ROOT = resolve(import.meta.dirname, '../../../../../..');
const SELF = resolve(import.meta.filename);

/**
 * every processor SDK the tree is swept for, and the one module that may import it.
 *
 * a table rather than "these files may import any SDK", which is the shape that would let the
 * PayPal adapter reach for `stripe` and the Stripe one reach for PayPal — each adapter translates
 * one processor's vocabulary, and a file importing both is a file translating neither.
 *
 * `@stripe/stripe-js` and `@paypal/paypal-js` are deliberately not here. those are the browser
 * loaders the donation form's element uses (packages/form), which is a different package with a
 * different rule — the anchoring below is what keeps a specifier ending at the quote from matching
 * one of them.
 */
const GUARDED: { specifier: string; adapter: string }[] = [
	{ specifier: 'stripe', adapter: resolve(import.meta.dirname, 'stripe.ts') },
	{
		specifier: '@paypal/paypal-server-sdk',
		adapter: resolve(import.meta.dirname, 'paypal.ts')
	}
];

const ADAPTERS = new Set(GUARDED.map((entry) => entry.adapter));

const EXTENSIONS = ['.ts', '.tsx', '.js', '.jsonc'];

/**
 * directories with nothing authored in them.
 *
 * `node_modules` holds the package itself and every re-export of it, so scanning it would report
 * the dependency as its own violation. most of the rest are build output and runtime state —
 * generated from the files this scan already covers, and regenerated by commands that do not run
 * here, so a finding in one is either a duplicate or stale.
 *
 * `.claude` is the odd one and is the reason this list is documented: it holds tooling state, and
 * an agent working in an isolated git worktree leaves a second checkout of this repository under
 * `.claude/worktrees/`. that checkout has its own `stripe.ts` and its own copy of this file, so
 * scanning it reports this repository's own guards as violations of themselves and fails the suite
 * on a tree nobody has changed. the walk covers what this repository authors, and a checkout of it
 * is not that.
 */
const SKIP = new Set([
	'node_modules',
	'.claude',
	'.git',
	'.react-router',
	'.wrangler',
	'.vitest-attachments',
	'.vscode',
	'dist',
	'build'
]);

/** every authored source file in the repository, minus the adapters and this spec. */
function sourceFiles(dir: string, out: string[] = []): string[] {
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		if (SKIP.has(entry.name)) continue;
		const path = join(dir, entry.name);
		if (entry.isDirectory()) {
			sourceFiles(path, out);
		} else if (
			EXTENSIONS.some((e) => entry.name.endsWith(e)) &&
			!ADAPTERS.has(path) &&
			path !== SELF
		) {
			out.push(path);
		}
	}
	return out;
}

/**
 * three ways to reach a package, because a rule that knew only the first would be worth less than
 * no rule:
 *
 *   - `import … from 'stripe'` / `import 'stripe'`, in either quote style.
 *   - `import('stripe')`, which is the shape a "keep it out of the cold path" change reaches for.
 *   - `require('stripe')`.
 *
 * anchored on the specifier ending at the quote, so `@stripe/stripe-js`, `@paypal/paypal-js` and a
 * path inside either package would not match — none of those is the package being guarded, and a
 * rule that flagged them would be abandoned rather than fixed.
 *
 * built from the specifier rather than written out per package, so the second SDK is guarded by the
 * same three patterns as the first rather than by whichever two somebody remembered.
 */
function importers(specifier: string): { label: string; re: RegExp }[] {
	const quoted = `['"]${specifier.replaceAll('/', '\\/')}['"]`;
	return [
		{ label: 'static import', re: new RegExp(`\\bfrom\\s*${quoted}|\\bimport\\s*${quoted}`) },
		{ label: 'dynamic import', re: new RegExp(`\\bimport\\s*\\(\\s*${quoted}\\s*\\)`) },
		{ label: 'require', re: new RegExp(`\\brequire\\s*\\(\\s*${quoted}\\s*\\)`) }
	];
}

describe('one module per processor SDK is the only importer of it', () => {
	const files = sourceFiles(ROOT);

	it('finds source files to scan at all, across the whole repository', () => {
		// a guard on the guard: an empty list would make the assertion below pass vacuously, and a
		// wrong `ROOT` is exactly how that happens. one file from each package plus one from the
		// workspace root, so that a scan which silently stopped at any of those three boundaries
		// fails here.
		const names = files.map((f) => relative(ROOT, f));
		expect(names).toContain('packages/app/src/root.tsx');
		expect(names).toContain('packages/app/src/lib/server/payments/provider.ts');
		expect(names).toContain('packages/app/vite.config.ts');
		expect(names).toContain('packages/form/src/element.ts');
		expect(names).toContain('biome.jsonc');
		expect(names.length).toBeGreaterThan(10);
	});

	it('does not descend into .claude/, where a second checkout of this repository can sit', () => {
		// an agent working in an isolated git worktree leaves the checkout under
		// `.claude/worktrees/`, and a checkout is a whole copy of this repository: its
		// `src/lib/server/payments/stripe.ts` reads as a second importer, and so does its copy of
		// this file. the suite then fails on `main` over a tree nobody changed, and the only fix
		// anyone can find is to delete the worktree.
		//
		// asserted against a fixture rather than against the repository, because `.claude/` is
		// absent from a clean checkout: a claim about a directory that is not there passes without
		// reading anything, which is the same silence the case above exists to refuse.
		const root = mkdtempSync(join(tmpdir(), 'sole-importer-'));
		try {
			const checkout = join(root, '.claude', 'worktrees', 'agent-1', 'src');
			mkdirSync(checkout, { recursive: true });
			writeFileSync(join(checkout, 'stripe.ts'), "import Stripe from 'stripe';\n");
			mkdirSync(join(root, 'src'), { recursive: true });
			writeFileSync(join(root, 'src', 'kept.ts'), 'export const kept = true;\n');

			expect(sourceFiles(root).map((f) => relative(root, f))).toEqual([join('src', 'kept.ts')]);
		} finally {
			rmSync(root, { recursive: true, force: true });
		}
	});

	it.each(GUARDED)(
		'finds no import of `$specifier` outside its own adapter',
		({ specifier, adapter }) => {
			const offenders: string[] = [];
			for (const file of files) {
				const source = readFileSync(file, 'utf8');
				for (const { label, re } of importers(specifier)) {
					if (re.test(source)) offenders.push(`${relative(ROOT, file)} (${label})`);
				}
			}
			// the message is the whole value of this test: it is read by whoever just added the import.
			expect(
				offenders,
				`these modules import \`${specifier}\` directly: ${offenders.join(', ')}. only ${relative(ROOT, adapter)} may — take \`PaymentProvider\` from src/lib/server/payments/provider.ts and build one with \`createPaymentProviders(platform.env).for(…)\`. if the port does not expose what you need, widen the port: a second importer is a second translation of that processor's vocabulary, and the two disagree where nobody looks.`
			).toEqual([]);
		}
	);

	it.each(GUARDED)('matches every way of importing `$specifier`', ({ specifier }) => {
		// without this, a typo'd regex that matches nothing anywhere would report a clean tree
		// forever — and the patterns are built from the specifier, so a specifier that needs
		// escaping (`@paypal/paypal-server-sdk` has a slash in it) is exactly where that happens.
		const written = [
			`import Sdk from '${specifier}';`,
			`import "${specifier}";`,
			`const sdk = await import('${specifier}');`,
			`const sdk = require('${specifier}');`
		];

		for (const line of written) {
			expect(
				importers(specifier).some(({ re }) => re.test(line)),
				`no pattern matched: ${line}`
			).toBe(true);
		}
	});

	it.each(GUARDED)(
		'matches `$specifier` in its own adapter, so the patterns work on real source',
		({ specifier, adapter }) => {
			// the case above is written from the same idea as the patterns, so it cannot catch a rule
			// that is wrong about how an import is actually spelled in this repository. this one reads
			// files nobody wrote for it — which is also what holds each adapter to importing the SDK
			// it is the sole importer of, rather than standing empty beside a guard nothing tests.
			const source = readFileSync(adapter, 'utf8');
			expect(importers(specifier).some(({ re }) => re.test(source))).toBe(true);
		}
	);
});
