import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

// the guard on "./stripe.ts is the only module that imports `stripe`".
//
// why this test exists. payments go through the `PaymentProvider` port and never Stripe directly
// (CLAUDE.md), and until this file that was enforced by nothing — a convention, which is a code
// review somebody has to remember to do. it is the same guard ../ledger/sole-writer.spec.ts holds
// over `INSERT`, written the same way, and the rule it protects is the one ../db/client.ts states
// about D1: everything else takes the interface, so the contract has exactly one place to be
// stated.
//
// what the rule buys, concretely. the SDK's vocabulary — seven PaymentIntent states, sixteen
// error classes, unix seconds, lowercase currencies, expandable fields that are sometimes id
// strings — stops at one file, and ./provider.ts is what the rest of the app reads. a second
// importer is a second translation of all of that, written by whoever needed one field in a hurry,
// and the two disagree in exactly the places nobody looks.
//
// the tempting shortcut this exists to catch is a route handler reaching for `stripe.refunds` or
// `stripe.webhooks` because the port does not expose what it needs yet. the answer is to widen the
// port, which is a reviewable change, rather than to open a second channel to the processor.
//
// it scans the whole repository rather than `src/`, because `src/` is not the whole repository:
// CLAUDE.md puts packages in `packages/*` consumable as source, and the root holds build and test
// configuration that is ordinary TypeScript and could import anything. a guard that stopped at
// `src/` would be silent about both.
//
// how it works: a source scan, not a runtime hook. a runtime one would only see the paths a test
// happens to exercise, and the importer that matters is exactly the one nobody wrote a test for.
// it reads text and can be fooled by a computed specifier — accepted, because what it defends
// against is a shortcut taken in a hurry, not an adversary.
//
// what is exempt: ./stripe.ts, and this file, which necessarily contains the pattern it searches
// for.

const ROOT = resolve(import.meta.dirname, '../../../../../..');
const ADAPTER = resolve(import.meta.dirname, 'stripe.ts');
const SELF = resolve(import.meta.filename);

const EXTENSIONS = ['.ts', '.tsx', '.js', '.jsonc'];

/**
 * directories with nothing authored in them.
 *
 * `node_modules` holds the package itself and every re-export of it, so scanning it would report
 * the dependency as its own violation. most of the rest are build output and runtime state —
 * generated from the files this scan already covers, and regenerated by commands that do not run
 * here, so a finding in one is either a duplicate or stale.
 *
 * `.claude` is the odd one and is the reason this list is documented: it holds tooling state, and
 * an agent working in an isolated git worktree leaves a second checkout of this repository under
 * `.claude/worktrees/`. that checkout has its own `stripe.ts` and its own copy of this file, so
 * scanning it reports this repository's own guards as violations of themselves and fails the suite
 * on a tree nobody has changed. the walk covers what this repository authors, and a checkout of it
 * is not that.
 */
const SKIP = new Set([
	'node_modules',
	'.claude',
	'.git',
	'.react-router',
	'.wrangler',
	'.vitest-attachments',
	'.vscode',
	'dist',
	'build'
]);

/** every authored source file in the repository, minus the adapter and this spec. */
function sourceFiles(dir: string, out: string[] = []): string[] {
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		if (SKIP.has(entry.name)) continue;
		const path = join(dir, entry.name);
		if (entry.isDirectory()) {
			sourceFiles(path, out);
		} else if (
			EXTENSIONS.some((e) => entry.name.endsWith(e)) &&
			path !== ADAPTER &&
			path !== SELF
		) {
			out.push(path);
		}
	}
	return out;
}

/**
 * three ways to reach the package, because a rule that knew only the first would be worth less
 * than no rule:
 *
 *   - `import … from 'stripe'` / `import 'stripe'`, in either quote style.
 *   - `import('stripe')`, which is the shape a "keep it out of the cold path" change reaches for.
 *   - `require('stripe')`.
 *
 * anchored on the specifier ending at the quote, so `@stripe/stripe-js` and a path inside the
 * package would not match — neither is this package, and a rule that flagged them would be
 * abandoned rather than fixed.
 */
const IMPORTERS: { label: string; re: RegExp }[] = [
	{ label: 'static import', re: /\bfrom\s*['"]stripe['"]|\bimport\s*['"]stripe['"]/ },
	{ label: 'dynamic import', re: /\bimport\s*\(\s*['"]stripe['"]\s*\)/ },
	{ label: 'require', re: /\brequire\s*\(\s*['"]stripe['"]\s*\)/ }
];

describe('stripe.ts is the only importer of the Stripe SDK', () => {
	const files = sourceFiles(ROOT);

	it('finds source files to scan at all, across the whole repository', () => {
		// a guard on the guard: an empty list would make the assertion below pass vacuously, and a
		// wrong `ROOT` is exactly how that happens. one file from each package plus one from the
		// workspace root, so that a scan which silently stopped at any of those three boundaries
		// fails here.
		const names = files.map((f) => relative(ROOT, f));
		expect(names).toContain('packages/app/src/root.tsx');
		expect(names).toContain('packages/app/src/lib/server/payments/provider.ts');
		expect(names).toContain('packages/app/vite.config.ts');
		expect(names).toContain('packages/form/src/element.ts');
		expect(names).toContain('biome.jsonc');
		expect(names.length).toBeGreaterThan(10);
	});

	it('does not descend into .claude/, where a second checkout of this repository can sit', () => {
		// an agent working in an isolated git worktree leaves the checkout under
		// `.claude/worktrees/`, and a checkout is a whole copy of this repository: its
		// `src/lib/server/payments/stripe.ts` reads as a second importer, and so does its copy of
		// this file. the suite then fails on `main` over a tree nobody changed, and the only fix
		// anyone can find is to delete the worktree.
		//
		// asserted against a fixture rather than against the repository, because `.claude/` is
		// absent from a clean checkout: a claim about a directory that is not there passes without
		// reading anything, which is the same silence the case above exists to refuse.
		const root = mkdtempSync(join(tmpdir(), 'sole-importer-'));
		try {
			const checkout = join(root, '.claude', 'worktrees', 'agent-1', 'src');
			mkdirSync(checkout, { recursive: true });
			writeFileSync(join(checkout, 'stripe.ts'), "import Stripe from 'stripe';\n");
			mkdirSync(join(root, 'src'), { recursive: true });
			writeFileSync(join(root, 'src', 'kept.ts'), 'export const kept = true;\n');

			expect(sourceFiles(root).map((f) => relative(root, f))).toEqual([join('src', 'kept.ts')]);
		} finally {
			rmSync(root, { recursive: true, force: true });
		}
	});

	it('finds no import of `stripe` outside src/lib/server/payments/stripe.ts', () => {
		const offenders: string[] = [];
		for (const file of files) {
			const source = readFileSync(file, 'utf8');
			for (const { label, re } of IMPORTERS) {
				if (re.test(source)) offenders.push(`${relative(ROOT, file)} (${label})`);
			}
		}
		// the message is the whole value of this test: it is read by whoever just added the import.
		expect(
			offenders,
			`these modules import the Stripe SDK directly: ${offenders.join(', ')}. only src/lib/server/payments/stripe.ts may — take \`PaymentProvider\` from src/lib/server/payments/provider.ts and build one with \`createPaymentProvider(platform.env)\`. if the port does not expose what you need, widen the port: a second importer is a second translation of Stripe's vocabulary, and the two disagree where nobody looks.`
		).toEqual([]);
	});

	it('matches the adapter itself, so the patterns are known to work', () => {
		// without this, a typo'd regex that matches nothing anywhere would report a clean tree
		// forever. stripe.ts is the one file that must match.
		const adapter = readFileSync(ADAPTER, 'utf8');
		expect(IMPORTERS.some(({ re }) => re.test(adapter))).toBe(true);
	});
});
