// what a spec needs to drive the Stripe adapter with no network: an HTTP client that answers from a
// script and records what the SDK sent, and a delivery signature computed the way Stripe computes one.
//
// not a spec itself — no pool's `include` matches this name. it imports nothing from `stripe`
// (./sole-importer.spec.ts): the client is structural, and the SDK it is handed is the real one, so
// the request under assertion is the one Stripe would receive, encoded by Stripe's own encoder.

/** one request the adapter made, as the assertions need to read it. */
export type Recorded = {
	readonly path: string;
	readonly method: string;
	readonly body: string;
	readonly headers: Record<string, string | number | string[]>;
};

/**
 * an HTTP client that answers from a script and remembers what it was asked.
 *
 * responses are consumed in order. running out is an error rather than a default, because a test
 * that made one more call than it scripted is a test whose subject did something it was not
 * asked to — and a permissive fallback would hide exactly that.
 */
export function recording(responses: readonly { status: number; json: unknown }[]) {
	const remaining = [...responses];
	const calls: Recorded[] = [];
	const httpClient = {
		getClientName: () => 'recording',
		async makeRequest(
			_host: string,
			_port: string,
			path: string,
			method: string,
			headers: Record<string, string | number | string[]>,
			requestData: string
		) {
			calls.push({ path, method, body: requestData, headers });
			const next = remaining.shift();
			if (!next) throw new Error(`unscripted request: ${method} ${path}`);
			return {
				getStatusCode: () => next.status,
				getHeaders: () => ({}),
				// an object rather than null: the SDK hangs `requestId` off whatever this returns
				// and exposes it as `lastResponse`, so a null here is a TypeError inside the SDK
				// before any assertion is reached.
				getRawResponse: () => ({}),
				// required by the interface and never reached: nothing this adapter calls streams a
				// response. omitted, the stub stops satisfying `HttpClientInterface` and every spec
				// that imports it fails to type-check rather than to run.
				toStream: () => null,
				// a fresh copy per answer. the SDK seals a non-writable `lastResponse` onto whatever
				// this returns, so handing back a shared literal twice throws on the second call
				// instead of answering it.
				toJSON: async () => structuredClone(next.json)
			};
		}
	};
	return { httpClient, calls };
}

/**
 * a `stripe-signature` header, computed rather than asked for.
 *
 * the scheme is published: `t=<unix seconds>,v1=<hex HMAC-SHA256 of "<t>.<body>" under the
 * signing secret>` — https://docs.stripe.com/webhooks#verify-manually. computing it in a test
 * is what makes the assertion mean something: a header generated by the same library that
 * verifies it proves only that the library agrees with itself, and would keep passing if both
 * halves drifted away from what Stripe actually sends.
 */
export async function sign(
	body: string,
	secret: string,
	atSeconds = Math.floor(Date.now() / 1000)
) {
	const encoder = new TextEncoder();
	const key = await crypto.subtle.importKey(
		'raw',
		encoder.encode(secret),
		{ name: 'HMAC', hash: 'SHA-256' },
		false,
		['sign']
	);
	const mac = await crypto.subtle.sign('HMAC', key, encoder.encode(`${atSeconds}.${body}`));
	const hex = [...new Uint8Array(mac)].map((b) => b.toString(16).padStart(2, '0')).join('');
	return `t=${atSeconds},v1=${hex}`;
}
